---

- name: Update and upgrade homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Add homebrew tap repository
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - "{{ homebrew_taps }}"

- name: Update homebrew
  homebrew:
    update_homebrew: yes

- name: Install brew packages
  homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    install_options: "{{ item.install_options | default('latest') }}"
  with_items:
    "{{ homebrew_packages }}"

- name: Install cask packages
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ homebrew_cask_packages }}"

