---

- hosts: localhost
  connection: local
  roles:
    - zprofile
    - homebrew_packages
    - mas_packages
    - dircolors
    - dotfiles
    - login_shell
    - setup_neovim
    - rbenv
  tasks:
    - name: which zsh
      shell: which zsh
      register: which_zsh

    - name: change login shell
      shell: >
        chpass -s {{ which_zsh.stdout }}
      register: result
      until: result.rc == 0
      retries: 3
