---

- name: Clone dotfiles repo
  git:
    repo: https://github.com/naokirin/dotfiles.git
    dest: "{{ ansible_env.HOME }}/dotfiles"

- name: Make .config directory
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory

- name: Link dotfiles
  file:
    src: "{{ ansible_env.HOME }}/dotfiles/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link
  with_items:
    - { src: zshrc, dest: .zshrc }
    - { src: tmux.conf, dest: .tmux.conf }
    - { src: .config/nvim, dest: .config/nvim }
    - { src: .gitconfig, dest: .gitconfig }

